#!/usr/bin/env python3
import sys
from pathlib import Path


def parse_gperf(path):
    rows = []
    in_words = False
    for raw in Path(path).read_text().splitlines():
        line = raw.strip()
        if line == '%%':
            if not in_words:
                in_words = True
                continue
            break
        if not in_words or not line or line.startswith('#'):
            continue
        if ',' not in line:
            continue
        name, enum_name = line.split(',', 1)
        name = name.strip()
        enum_name = enum_name.strip().split()[0]
        if name and enum_name:
            rows.append((name, enum_name))
    if not rows:
        raise SystemExit(f'no element rows found in {path}')
    return rows


def c_string(value):
    return value.replace('\\', '\\\\').replace('"', '\\"')


def render(rows, source_name):
    lines = [
        '/*',
        f' * Auto-generated from {source_name}.',
        ' * Keep generated by tools/gen_hubbub_element_type.py.',
        ' */',
        '',
        'static const struct element_type_map wordlist[] = {',
    ]
    for name, enum_name in rows:
        lines.append(f'\t{{ "{c_string(name)}", {enum_name} }},')
    lines.extend([
        '};',
        '',
        'static char hubbub_ascii_lower(char c)',
        '{',
        "\tif (c >= 'A' && c <= 'Z') {",
        "\t\treturn (char)(c + ('a' - 'A'));",
        '\t}',
        '\treturn c;',
        '}',
        '',
        'static int hubbub_ascii_case_equal(const char *a, const char *b, size_t len)',
        '{',
        '\tsize_t i;',
        '',
        '\tfor (i = 0; i < len; i++) {',
        '\t\tif (hubbub_ascii_lower(a[i]) != hubbub_ascii_lower(b[i])) {',
        '\t\t\treturn 0;',
        '\t\t}',
        '\t}',
        '',
        '\treturn 1;',
        '}',
        '',
        'static const struct element_type_map *hubbub_element_type_generated_lookup(',
        '\t\tconst char *str, size_t len)',
        '{',
        '\tsize_t i;',
        '',
        '\tfor (i = 0; i < sizeof(wordlist) / sizeof(wordlist[0]); i++) {',
        '\t\tconst char *name = wordlist[i].name;',
        '\t\tsize_t name_len = 0;',
        '',
        "\t\twhile (name[name_len] != '\\0') {",
        '\t\t\tname_len++;',
        '\t\t}',
        '',
        '\t\tif (name_len == len && hubbub_ascii_case_equal(name, str, len)) {',
        '\t\t\treturn &wordlist[i];',
        '\t\t}',
        '\t}',
        '',
        '\treturn NULL;',
        '}',
        '',
    ])
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 3:
        raise SystemExit('usage: gen_hubbub_element_type.py <element-type.gperf> <output.c>')
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    rows = parse_gperf(src)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(render(rows, str(src)), newline='\n')


if __name__ == '__main__':
    main()
